<?PHP  // michele.furlan@unipd.it   16 luglio 2024
define('TESTO_HOME_PAGE_USER', '<BR /><details><summary><B><--(clicca)</B> Schema database </summary><UL>'
  .'<LI>Nel compilare il FORM non utilizzare i simboli&nbsp;&nbsp;<B>\'&nbsp;&nbsp;\"&nbsp;&nbsp;@&nbsp;&nbsp;#&nbsp;&nbsp;(&nbsp;&nbsp;)&nbsp;&nbsp;[&nbsp;&nbsp;]&nbsp;&nbsp;{&nbsp;&nbsp;}</B>&nbsp;&nbsp;neppure per i nomi che prevedono l\'accento.</LI>'
  .'<LI><IMG src="./imma/schema_db.gif" /></LI>'
  .'</UL></details><BR />', TRUE);

define('TESTO_HOME_PAGE_ADMIN', '<details><summary><B><--(clicca)</B> Diagnostica </summary><UL>'
  .'<LI>ID SESSIONE: '.(isset($_SESSION['DB_SEME']) ? $_SESSION['DB_SEME'] : '').'</LI>'
  .'<LI>TIMEOUT_COMPILAZIONE_CARRELLO: '.TIMEOUT_COMPILAZIONE_CARRELLO.' minuti</LI>'
  .'<LI>DATA ORA SERVER: '.date('l d-F-Y H:i:s').'</LI>'
  .'<LI>DATA ORA LOCALE:&nbsp;<SPAN id="l_data_ora"></SPAN><SCRIPT>$("#l_data_ora").html(DataOraCorrente());</SCRIPT></LI>'
  .'<LI>TIMEZONE PHP SERVER: '.date_default_timezone_get().'</LI>'
  .'<LI>LAST_DATETIME_LOGIN: '.(isset($_SESSION['LAST_ACTIVITY']) ? date('d-F-Y H:i:s', $_SESSION['LAST_ACTIVITY']) : 'NO_SET_LAST_ACTIVITY').'</LI>'
  .'<LI>PHP SERVER CODIFICA CARATTERI: '.mb_internal_encoding().'</LI>'
  .'<LI>REMOTE_ADDRESS: '.@$_SERVER['REMOTE_ADDR'].'</LI>'
  .'<LI>PORTA REMOTA BROWSER: '.@$_SERVER['REMOTE_PORT'].'</LI>'
  .'<LI>HTTP_AGENT: '.@$_SERVER['HTTP_USER_AGENT'].'</LI>'
  .'<LI>HTTP_ACCEPT_LANGUAGE: '.(isset($_SERVER['HTTP_ACCEPT_LANGUAGE']) ? $_SERVER['HTTP_ACCEPT_LANGUAGE'] : 'NO_SET_LANGUAGE').'</LI>'
  .'<LI>PHP SERVER VERSION: '.phpversion().'</LI>'
  .'<LI>HOST_NAME: '.php_uname('n').'</LI>'
  .'<LI>OS_NAME_RELEASE: '.php_uname('s').'&nbsp;'.php_uname('r').'</LI>'
  .'<LI>MYSQL SERVER VERSION: '.$conn_obj->conn->client_version.'</LI>'
  .'<LI><pre style="white-space: pre-wrap; word-break: keep-all; overflow: auto;">'
  .'Non vengono mostrati all\'utente prodotti per i quali non esiste giacenza di articoli'
  .' in magazzino e che non sono ordinabili perche\' il preventivo e\' scaduto.'
  .' Se ci sono articoli in un preventivo valido, essi sono sempre inseribili nel carrello anche'
  .' se in quantita\' negativa o zero.'
  .' Nel seguito s\' intende per quantita disponibile in magazzino per articolo: il numero'
  .' di articoli rimasti disponibili al netto degli articoli gia\' caricati nei carrelli,'
  .' non il numero effettivamente presente in magazzino. La quantita\' effettivamente giacente di'
  .' un articolo e\' data dalla somma della quantita disponibile sopra definita piu\' la quantita di articolo'
  .' non ancora ritirata presente dei diversi carrelli.'
  .' Algoritmo di selezione degli articoli da immettere nel carrello: il riempimento del carrello avviene'
  .' selezionando la quantita\' desiderata di prodotto; se devo aggiungere la quantita di un determinato'
  .' prodotto nel carrello considero che possono esistere ad esso associati uno o piu\' articoli.'
  .' Prendo l\' articolo con il prezzo piu\' alto se la quantita\' disponibile e\' positiva;'
  .' in questo caso non serve verificare che ci sia un preventivo attivo perche\''
  .' il prodotto e\' in magazzino e non caricato in altri carrelli. La quantita\' massima'
  .' caricabile nel carrello di tale articolo sara\' pari alla quantita\' disponibile non'
  .' essendo l\'articolo ordinabile. Una volta caricata per ipotesi la quantita'
  .' che pone a zero la quantita\' disponibile in magazzino di tale primo articolo selezionato, il'
  .' successivo articolo viene scelto con la stesso citerio del primo se ne'
  .' esiste una quantita positiva. Nel caso non vi siano piu\' articoli in quantita positiva'
  .' e dovendo ancora completare la quantita richiesta di prodotto si seleziona l\'articolo'
  .' con il prezzo piu\' basso, e che sia presente in un preventivo non scaduto. Nel caso di piu\''
  .' articoli presenti con lo stesso prezzo viene selezionato l\'articolo con la maggiore quantita disponibile.'
  .' Nel caso si debba sottrare una quantita\' di prodotto dal carrello si procede'
  .' selezionando l\' articolo inserito per ultimo nel carrello.'
  .'</pre></LI></UL></details>' , TRUE);

$html_SQL = <<<HTML

<style type="text/css">
span {
    font-family: 'Courier New';
    font-size: 10pt;
    color: #000000;
}
.sc0 {
}
.sc1 {
    color: #008000;
}
.sc4 {
    color: #FF8000;
}
.sc5 {
    font-weight: bold;
    color: #0000FF;
}
.sc10 {
    font-weight: bold;
    color: #000080;
}
.sc11 {
}
</style>

<div style="float: left; white-space: pre; line-height: 1; background: #FFFFFF; padding:3px;"><span class="sc1">/* SELECT aggiorna_articoli_in_carrello(id_prod, quantita, id_sess); -- riceve la quantita di prodotto da ordinare con il relativo id, e aggiorna il carrello utente */</span><span class="sc0">
</span><span class="sc5">DROP</span><span class="sc0"> </span><span class="sc5">FUNCTION</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc5">EXISTS</span><span class="sc0"> </span><span class="sc11">aggiorna_articoli_in_carrello</span><span class="sc10">;</span><span class="sc0">
</span><span class="sc11">DELIMITER</span><span class="sc0"> $$
</span><span class="sc5">CREATE</span><span class="sc0"> </span><span class="sc11">DEFINER</span><span class="sc10">=</span><span class="sc0">`</span><span class="sc11">root</span><span class="sc0">`@`</span><span class="sc11">localhost</span><span class="sc0">` </span><span class="sc5">FUNCTION</span><span class="sc0"> </span><span class="sc11">aggiorna_articoli_in_carrello</span><span class="sc10">(</span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc11">UNSIGNED</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">qt_prod</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc0"> </span><span class="sc5">BIGINT</span><span class="sc0"> </span><span class="sc11">UNSIGNED</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">RETURNS</span><span class="sc0"> </span><span class="sc5">TINYINT</span><span class="sc0">
</span><span class="sc5">READS</span><span class="sc0"> </span><span class="sc5">SQL</span><span class="sc0"> </span><span class="sc5">DATA</span><span class="sc0">
</span><span class="sc5">DETERMINISTIC</span><span class="sc0">
</span><span class="sc5">BEGIN</span><span class="sc0">

  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">quantita_art_presente</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc5">NULL</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc11">UNSIGNED</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">n_art</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc11">UNSIGNED</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc5">INT</span><span class="sc0"> </span><span class="sc11">UNSIGNED</span><span class="sc0"> </span><span class="sc5">DEFAULT</span><span class="sc0"> </span><span class="sc4">1000</span><span class="sc10">;</span><span class="sc0">   </span><span class="sc1">/* Limite iterativo per sicurezza nel ciclo while */</span><span class="sc0">
  </span><span class="sc5">DECLARE</span><span class="sc0"> </span><span class="sc5">CONTINUE</span><span class="sc0"> </span><span class="sc11">HANDLER</span><span class="sc0"> </span><span class="sc5">FOR</span><span class="sc0"> </span><span class="sc5">SQLEXCEPTION</span><span class="sc0">     </span><span class="sc1">/* Gestore dell'errore */</span><span class="sc0">
  </span><span class="sc5">BEGIN</span><span class="sc0">
     </span><span class="sc5">RETURN</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">);</span><span class="sc0">
  </span><span class="sc5">END</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc1">/* qt_da_caricare indica la quantita' di prodotto mancante data dalla differenza con la quantita di articoli eventualemente gia' presenti per il prodotto selezionato */</span><span class="sc0">
</span><span class="sc1">/* Osservare che ci possono essere articoli nel carrello appartenenti a prodotti diversi - QUINDI e' necessario filtrare per prodotto id_prod */</span><span class="sc0">
</span><span class="sc1">/* SELECT * FROM Products WHERE EXISTS (SELECT Price FROM Products WHERE Price &gt; 50); */</span><span class="sc0">
</span><span class="sc1">/* La quantita da caricare non puo' essere maggiore di maxordine specificata per il prodotto */</span><span class="sc0">
</span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_prod</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">LEAST</span><span class="sc10">((</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">maxordine</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">prodotti</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">),</span><span class="sc0"> </span><span class="sc11">qt_prod</span><span class="sc10">));</span><span class="sc0">
</span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">qt_prod</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">(</span><span class="sc4">0</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">COUNT</span><span class="sc10">(*)</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc10">),</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">SUM</span><span class="sc10">(</span><span class="sc11">quantita</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc10">))));</span><span class="sc0">

</span><span class="sc1">/* Non dovrebbe mai andare a 0 perche' solo se c'e' un cambio di quantita si scatena l'evento onchange sul controllo */</span><span class="sc0">
</span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">  </span><span class="sc1">/* Nulla di fatto - anche se non dovrebbe accadere che l'evento onchange si scateni se non cambia la quantita */</span><span class="sc0">
   </span><span class="sc5">RETURN</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">);</span><span class="sc0">
</span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">  </span><span class="sc1">/* Devo AGGIUNGERE quantita di prodotto nel carrello */</span><span class="sc0">

  </span><span class="sc5">WHILE</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">DO</span><span class="sc0">

  </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">n_art</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">COUNT</span><span class="sc10">(*)</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">articoli</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">in_uso</span><span class="sc10">);</span><span class="sc0">  </span><span class="sc1">/* Prelievo prima gli articoli dove la quantita disponibile e' positiva */</span><span class="sc0">
  </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">n_art</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">  </span><span class="sc1">/* Non ci sono quantita positive quindi prendo un articolo da preventivo valido con prezzo piu' basso */</span><span class="sc0">
      </span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc10">.</span><span class="sc11">id</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc10">.</span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc5">INTO</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">articoli</span><span class="sc0"> </span><span class="sc5">AS</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc0"> </span><span class="sc5">JOIN</span><span class="sc0"> </span><span class="sc11">preventivi</span><span class="sc0"> </span><span class="sc5">AS</span><span class="sc0"> </span><span class="sc11">P</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc10">.</span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc10">.</span><span class="sc11">in_uso</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">P</span><span class="sc10">.</span><span class="sc11">datapreventivo</span><span class="sc0"> </span><span class="sc10">&lt;=</span><span class="sc0"> </span><span class="sc11">CURDATE</span><span class="sc10">()</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">P</span><span class="sc10">.</span><span class="sc11">datascadenza</span><span class="sc0"> </span><span class="sc10">&gt;=</span><span class="sc0"> </span><span class="sc11">CURDATE</span><span class="sc10">()</span><span class="sc0"> </span><span class="sc5">ORDER</span><span class="sc0"> </span><span class="sc5">BY</span><span class="sc0"> </span><span class="sc11">A</span><span class="sc10">.</span><span class="sc11">prezzo</span><span class="sc0"> </span><span class="sc5">ASC</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">ELSE</span><span class="sc0">  </span><span class="sc1">/* Da l'articolo con la minore quantita positiva prelevo quello con il prezzo piu' alto */</span><span class="sc0">
      </span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc5">INTO</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">articoli</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">in_uso</span><span class="sc0"> </span><span class="sc5">ORDER</span><span class="sc0"> </span><span class="sc5">BY</span><span class="sc0"> </span><span class="sc11">prezzo</span><span class="sc0"> </span><span class="sc5">DESC</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc5">DESC</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">
  </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

    </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">  </span><span class="sc1">/* E stato trovato un articolo in quantita ancora disponibile in magazzino */</span><span class="sc0">
         </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0">  </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">
            </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc10">);</span><span class="sc0">
            </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc10">));</span><span class="sc0">  </span><span class="sc1">/* Quantita residua di prodotto da caricare nel carello per il caricare la quale sara necessario trovare un nuovo articolo */</span><span class="sc0">
         </span><span class="sc5">ELSE</span><span class="sc0">
            </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc10">);</span><span class="sc0">  </span><span class="sc1">/* Posso caricare tutto */</span><span class="sc0">
            </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">);</span><span class="sc0">
         </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">
    </span><span class="sc5">ELSE</span><span class="sc0">  </span><span class="sc1">/* Quando la quantita e' zero o inferiore carico tutta la quantita necessaria essendo attivo un preventivo
          e l'articolo selezionato ha il prezzo piu' basso tra quelli disponibili appartenenti allo stesso prodotto */</span><span class="sc0">
         </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc10">);</span><span class="sc0">
         </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">);</span><span class="sc0">  </span><span class="sc1">/* Non serve ripetere il loop */</span><span class="sc0">
    </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc1">/* Devo filtrare la sessione perche' ci sono carrelli di piu' utenti */</span><span class="sc0">
    </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita_art_presente</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">MAX</span><span class="sc10">(</span><span class="sc11">quantita</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">id_articolo</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">);</span><span class="sc0"> </span><span class="sc1">/* Quantita gia' presente dello stesso articolo */</span><span class="sc0">
    </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">+</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">(</span><span class="sc5">ISNULL</span><span class="sc10">(</span><span class="sc11">quantita_art_presente</span><span class="sc10">),</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">quantita_art_presente</span><span class="sc10">)));</span><span class="sc0">  </span><span class="sc1">/* Includo anche la quantita di articolo gia presente */</span><span class="sc0">
</span><span class="sc1">/* Devo togliere dalla quantita disponibile in magazzino dell'articolo per i futuri carrelli la quantita caricata ora nel carrello */</span><span class="sc0">

    </span><span class="sc5">UPDATE</span><span class="sc0"> </span><span class="sc11">articoli</span><span class="sc0"> </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">

    </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">quantita_art_presente</span><span class="sc0"> </span><span class="sc5">IS</span><span class="sc0"> </span><span class="sc5">NULL</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">
         </span><span class="sc5">INSERT</span><span class="sc0"> </span><span class="sc5">INTO</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc10">(</span><span class="sc11">id_carrello</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_articolo</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">VALUES</span><span class="sc10">((</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelli</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc10">),</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc10">);</span><span class="sc0">
    </span><span class="sc5">ELSE</span><span class="sc0">
</span><span class="sc1">/* qt_carica incorpora la nuova quantita piu' la preesistente dell'articolo nel carrello (se esiste) */</span><span class="sc0">
         </span><span class="sc5">UPDATE</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">
    </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

    </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">));</span><span class="sc0">
  </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">WHILE</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc5">ELSE</span><span class="sc0">  </span><span class="sc1">/* DEVO sottrarre quantita di prodotto */</span><span class="sc0">

  </span><span class="sc5">WHILE</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">&gt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">&lt;</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">DO</span><span class="sc0">   </span><span class="sc1">/* da caricare a magazzino ripristinando la scorta dell articolo ! */</span><span class="sc0">
     </span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc5">INTO</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">,</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">id_prodotto</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_prod</span><span class="sc0"> </span><span class="sc5">ORDER</span><span class="sc0"> </span><span class="sc5">BY</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc5">DESC</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">  </span><span class="sc1">/* Elimino gli ultimi inseriti */</span><span class="sc0">

     </span><span class="sc5">IF</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc10">&gt;=</span><span class="sc0"> </span><span class="sc5">ABS</span><span class="sc10">(</span><span class="sc11">q_da_caricare</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">THEN</span><span class="sc0">
        </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">q_ta</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc5">ABS</span><span class="sc10">(</span><span class="sc11">q_da_caricare</span><span class="sc10">)));</span><span class="sc0">
        </span><span class="sc5">UPDATE</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">  </span><span class="sc1">/* Diminuisco quantita articolo nel carrello */</span><span class="sc0">
        </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc5">ABS</span><span class="sc10">(</span><span class="sc11">q_da_caricare</span><span class="sc10">));</span><span class="sc0">
        </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc10">);</span><span class="sc0">  </span><span class="sc1">/* Non servira reiterare il LOOP */</span><span class="sc0">
     </span><span class="sc5">ELSE</span><span class="sc0">
        </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">q_da_caricare</span><span class="sc0"> </span><span class="sc10">+</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc10">));</span><span class="sc0">  </span><span class="sc1">/* diminuisco la quantita di prodotto da ricaricare in magazzino e svuotare dal carrello */</span><span class="sc0">
        </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">q_ta</span><span class="sc10">);</span><span class="sc0">
        </span><span class="sc5">UPDATE</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">
     </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

     </span><span class="sc5">UPDATE</span><span class="sc0"> </span><span class="sc11">articoli</span><span class="sc0"> </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">+</span><span class="sc0"> </span><span class="sc11">qt_carica</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">id_articolo</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">id</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_a</span><span class="sc10">)</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">   </span><span class="sc1">/* Ripristino quantita in magazzino */</span><span class="sc0">
</span><span class="sc1">/* Rimuovo dal carrello tutti gli articoli la cui quantita' e' stata azzerrata */</span><span class="sc0">
     </span><span class="sc5">DELETE</span><span class="sc0"> </span><span class="sc5">FROM</span><span class="sc0"> </span><span class="sc11">carrelloart</span><span class="sc0"> </span><span class="sc5">WHERE</span><span class="sc0"> </span><span class="sc11">quantita</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc4">0</span><span class="sc0"> </span><span class="sc5">AND</span><span class="sc0"> </span><span class="sc11">id_sessione</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc11">id_sess</span><span class="sc0"> </span><span class="sc5">LIMIT</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">;</span><span class="sc0">

     </span><span class="sc5">SET</span><span class="sc0"> </span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">=</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc11">max_loop</span><span class="sc0"> </span><span class="sc10">-</span><span class="sc0"> </span><span class="sc4">1</span><span class="sc10">));</span><span class="sc0">
  </span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">WHILE</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc5">END</span><span class="sc0"> </span><span class="sc5">IF</span><span class="sc10">;</span><span class="sc0">

</span><span class="sc5">RETURN</span><span class="sc0"> </span><span class="sc10">(</span><span class="sc5">SELECT</span><span class="sc0"> </span><span class="sc11">q_da_caricare</span><span class="sc10">);</span><span class="sc0">  </span><span class="sc1">/* Deve ritornare 0 al termine dei LOOP */</span><span class="sc0">
</span><span class="sc5">END</span><span class="sc0"> $$
</span><span class="sc11">DELIMITER</span><span class="sc0"> </span><span class="sc10">;</span><span class="sc0">
</span></div>

HTML;

define('TESTO_RETE_DISC', '<BR /><HR style="height:4px;border-width:0;width:100%;background-color:black;"><details><summary><B><--(clicca)</B>&nbsp;SQL ISTRUZIONI CARICO ARTICOLI NEL CARRELLO</summary>'
       .$html_SQL.'</details>', TRUE);
?>